---
package_install_retry: 3
package_install_retry_delay: 10

macports:
  present: []
    #- chunkwm
    #- skhd

  selections:
    - group: helm
      version: helm2.14
    - group: kubectl
      version: kubectl1.13
    - group: maven
      version: maven3
    - group: pip
      version: pip37
    - group: python
      version: python37
    - group: python2
      version: python27
    - group: python3
      version: python37
    - group: ruby
      version: ruby24
    - group: virtualenv
      version: virtualenv27
...
