---
dependencies:
  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: bumpversion
        - package: bump2version
        - package: ignr
        - package: pip-autoremove
        - package: pipdeptree
    tags:
      - common
      - common_tools
      - dotlocal_pyenv_install
      - install
  - role: homeshick
    vars:
      castles:
        - uri: git@bitbucket.org:pedrohdz/dr-home.git
        - uri: git@github.com:pedrohdz/dr-tmux.git
        - uri: git@github.com:pedrohdz/dr-vimfiles.git
    tags:
      - common
      - common_homeshick
      - homeshick
      - install
...
