---
dependencies:
  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: bumpversion
        - package: ignr
          version: '1.1'
          python_version: python27
        - package: pip-autoremove
        - package: pipdeptree
    tags:
      - common
      - common_tools
  - role: homeshick
    vars:
      castles:
        - uri: git@bitbucket.org:pedrohdz/dr-home.git
        - uri: git@github.com:pedrohdz/dr-tmux.git
        - uri: git@github.com:pedrohdz/dr-vimfiles.git
    tags:
      - common
      - common_homeshick
...
