---
dependencies:
  - role: dotlocal-pyenv-install
    packages:
      - package: bumpversion
      - package: ignr
        version: '1.1'
        python_version: python27
      - package: pip-autoremove
      - package: pipdeptree
    tags:
      - common
      - common_tools
...
