---
- name: Include global variables
  include_tasks: ../../globals.yaml

- name: "Install Python package {{ package_name }} {{ version }} in a virtual environment"
  pip:
    name: "{{ package_name }}"
    version: "{{ version if version != 'LATEST' else '' }}"
    umask: '7077'
    virtualenv: "~/.local/opt/python/{{ package_name }}-{{ version }}"
    virtualenv_command: "{{ venv_command[python_version] }}"
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
  vars:
    venv_command:
      python27: "{{ virtualenv_command_py27 }}"
      python3: "{{ virtualenv_command_py3 }}"
- name: "Create a symlink to active version: {{ package_name }}-{{ version }}"
  file:
    src: "{{ package_name }}-{{ version }}"
    dest: "~/.local/opt/python/{{ package_name }}"
    state: link
- name: "Create symlinks to the bin files: {{ bin_files }}"
  file:
    src: "../opt/python/{{ package_name }}/bin/{{ item }}"
    dest: "~/.local/bin/{{ item }}"
    state: link
  loop: "{{ bin_files }}"
...
