---
- name: Statically import global variables
  import_tasks: ../../globals.yaml

- name: Removing Python venvs
  include_tasks: process-absent.yaml
  when: absent is defined
  vars:
    package: "{{ absent_item['package'] }}"
    bin_files: "{{ absent_item['bin_files'] if 'bin_files' in absent_item else [ absent_item['package'] ] }}"
  loop: "{{ absent }}"
  loop_control:
    loop_var: absent_item

- name: Installing multiple Python venvs
  include_tasks: process.yaml
  when: packages is defined
  vars:
    package: "{{ package_item['package'] }}"
    python_version: "{{ package_item['python_version'] if 'python_version' in package_item else 'python3' }}"
    version: "{{ package_item['version'] if 'version' in package_item else 'LATEST' }}"
    bin_files: "{{ package_item['bin_files'] if 'bin_files' in package_item else [ package_item['package'] ] }}"
  loop: "{{ packages }}"
  loop_control:
    loop_var: package_item

...
