---
- name: "Install Python package {{ package }} {{ version }} in a virtual environment ({{ python_version }})"
  pip:
    name: "{{ package }}"
    version: "{{ version if version != 'LATEST' else '' }}"
    umask: '7077'
    virtualenv: "~/.local/opt/python/{{ package }}-{{ version }}"
    virtualenv_command: "{{ venv_command[python_version] }}"
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
  vars:
    venv_command:
      python27: "{{ virtualenv_command_py27 }}"
      python3: "{{ virtualenv_command_py3 }}"
- name: "Create a symlink to active version: {{ package }}-{{ version }}"
  file:
    src: "{{ package }}-{{ version }}"
    dest: "~/.local/opt/python/{{ package }}"
    state: link
- name: "Create symlinks to the bin files: {{ bin_files }}"
  file:
    src: "../opt/python/{{ package }}/bin/{{ bin_file_item }}"
    dest: "~/.local/bin/{{ bin_file_item }}"
    state: link
  loop: "{{ bin_files }}"
  loop_control:
    loop_var: bin_file_item
...
