---
- hosts: all
  roles:
    - role: setup_debian
      when: sudo_access and (ansible_facts['os_family'] | lower == "debian")
    - role: common

- hosts: workstation
  roles:
    - workstation

- hosts:
    - dev
    - workstation
  roles:
    - dev-all

- hosts:
    - devops
    - workstation
  roles:
    - devops
...
