---
- hosts: all
  roles:
    - role: setup_debian
      when: sudo_access and (ansible_facts['os_family'] | lower == "debian")

- hosts: workstation
  roles:
    - workstation

- hosts: dev
  roles:
    - dev-all

- hosts: devops
  roles:
    - devops
...
