---
- hosts: all
  roles:
    - role: pyvenv-apps
  #  - role: setup_debian
  #    when: sudo_access and (ansible_facts['os_family'] | lower == "debian")
  #  - role: owned-prepare
  #    when: owned | default(false)
  #  - role: managed
  #    when: managed | default(false)
  #  - role: owned
  #    when: owned | default(false)
  vars:
    pyvenv_apps_become_for_all: true

#- hosts: workstation
#  roles:
#    - workstation
#
#- hosts: dev
#  roles:
#    - dev-all
#
#- hosts: devops
#  roles:
#    - devops
...
