---
- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution | lower }}-globals.yaml"
    - "vars/{{ ansible_os_family | lower }}-globals.yaml"
...
