---
- name: Include global variables
  include_tasks: ../../globals.yaml
- name: Gather non-os specific variables
  include_vars: vars/no_arch.yaml

# ----
# awscli
# ----
- name: Install awscli
  pip:
    name: awscli
    version: "{{ awscli_version }}"
    virtualenv: "~/.local/lib/python/awscli-{{ awscli_version }}"
    virtualenv_command: "{{ virtualenv_command_py3 }}"
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
- name: Create awscli version symlink
  file:
    src: "awscli-{{ awscli_version }}"
    dest: ~/.local/lib/python/awscli
    state: link
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
- name: Create awscli aws symlink
  file:
    src: ../lib/python/awscli/bin/aws
    dest: ~/.local/bin/aws
    state: link
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
- name: Create awscli aws_completer symlink
  file:
    src: ../lib/python/awscli/bin/aws_completer
    dest: ~/.local/bin/aws_completer
    state: link
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
...
