---
dependencies:
  - role: dev-common

  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: flake8
        - package: future
          bin_files:
            - futurize
            - pasteurize
        - package: isort
        - package: tabulate
        - package: tox
    tags:
      - dev_python
      - dev_python_tools

  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: pylint
    tags:
      - dev_python
      - dev_python_tools
    when: (ansible_facts['os_family'] | lower) != 'debian'
...
