---
- name: Install requested MacPorts ports
  macports:
    name: "{{ item['port'] }}"
    variant: "{{ item['variant'] if 'variant' in item else '' }}"
    state: "present"
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
  loop: "{{ macports.present | default([]) }}"
  become: true
- name: Uninstall certain MacPorts ports
  macports:
    name: "{{ item['port'] }}"
    state: "absent"
  loop: "{{ macports.absent | default([]) }}"
  become: true
...
