---
- name: Install requested MacPorts ports
  macports:
    name: "{{ macports.present | default([]) }}"
    state: "present"
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
  become: true

- name: Install requested MacPorts ports variants
  macports:
    name: "{{ item['port'] }}"
    variant: "{{ item['variant'] }}"
    state: "present"
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
  loop: "{{ macports.present_variants | default([]) }}"
  become: true

# TODO - Just join the list of ports to uninstall to avoid errors.
- name: Uninstall unwanted MacPorts ports
  macports:
    name: "{{ macports.absent | default([]) }}"
    state: "absent"
  become: true
...
