---
dependencies:
  - role: dev-common
    tags:
      - dev_nodejs
  - role: homeshick
    vars:
      castles:
        - uri: git@github.com:pedrohdz/dr-vimfiles-nodejs.git
    tags:
      - dev_nodejs
      - dev_nodejs_homeshick
      - homeshick
      - install
  - role: dotlocal-nodejs-install
    vars:
      modules:
        - module: instant-markdown-d
          version: 0.1.1
          bin_files:
            - instant-markdown-d
            - markdown-it
        - module: joplin
          version: LATEST
          bin_files:
            - joplin
    tags:
      - dev_nodejs
      - dev_nodejs_tools
      - dotlocal_nodejs_install
      - install
...
