---
- name: "Install Homesick castle {{ name }} ({{ uri }})"
  shell: >-
    umask 7077 ;
    ~/.homesick/repos/homeshick/bin/homeshick clone --batch {{ uri }}
    && ~/.homesick/repos/homeshick/bin/homeshick link --force --batch {{ name }}
  args:
    creates: "~/.homesick/repos/{{ name }}"
...
