---
- name: Install Homesick
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: ~/.homesick/repos/homeshick
    version: master
    update: false
    accept_hostkey: false
    umask: '7077'
- name: Install Homesick castle
  shell: >-
    umask 7077 ;
    {{ '~/.homesick/repos/homeshick/bin/homeshick clone --batch {}'.format(item['uri']) }}
    && {{ '~/.homesick/repos/homeshick/bin/homeshick link --force --batch {}'.format(item['name']) }}
  args:
    creates: "{{ '~/.homesick/repos/{}'.format(item['name']) }}"
  loop: "{{ homeshick_castles }}"
...
