---
# ----
# rope/ropevim
# ----
- name: Install rope
  pip:
    name: rope
    executable: /opt/local/bin/pip3
    extra_args: --user
    umask: '7077'
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
- name: Install ropemode
  pip:
    name: ropemode
    executable: /opt/local/bin/pip3
    extra_args: --user
    umask: '7077'
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
- name: Install ropevim
  pip:
    name: ropevim
    executable: /opt/local/bin/pip3
    extra_args: --user
    umask: '7077'
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"

# ----
# Jedi
# ----
- name: Install jedi
  pip:
    name: jedi
    executable: /opt/local/bin/pip3
    extra_args: --user
    umask: '7077'
  register: task_result
  until: task_result is succeeded
  retries: "{{ package_install_retry }}"
  delay: "{{ package_install_retry_delay }}"
...
