---
# ----
# Import variables
# ----
- name: Include global variables
  include_tasks: ../../globals.yaml
- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution | lower }}.yaml"
    - "vars/{{ ansible_os_family | lower }}.yaml"

# ----
# jp - JMESPath
# ----
- name: Install JMESPath jp
  get_url:
    url: "https://github.com/jmespath/jp/releases/download/{{ jmespath_jp_version }}/jp-{{ go_platform }}-amd64"
    dest: "~/.local/bin/jp-{{ go_platform }}-amd64+{{ jmespath_jp_version }}"
    checksum: "{{ jmespath_jp_checksum }}"
    mode: '0500'
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
- name: Create JMESPath jp symlink
  file:
    src: "~/.local/bin/jp-{{ go_platform }}-amd64+0.1.3"
    dest: ~/.local/bin/jp
    state: link
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
...
