---
- name: Process MacPorts selections
  include_tasks: lib/macports-select.yaml
  vars:
    group: "{{ item['group'] }}"
    version: "{{ item['version'] }}"
  loop: "{{ macports.selections }}"
...
