---
dependencies:
  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: sqlparse
          bin_files:
            - sqlformat
    tags:
      - dev_common
      - dev_common_tools
...
