---
dependencies:
  - role: common
  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: awscli
          version: '1.16.81'
          bin_files:
            - aws
            - aws_completer
        - package: jmespath-terminal
          version: '0.2.1'
          bin_files:
            - jpterm
        - package: netaddr
        - package: yamllint
          version: '1.13.0'
    tags:
      - devops
      - devops_tools
      - dotlocal_pyenv_install
      - install
  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: ansible-lint
          version: '4.0.0'
    when: (ansible_facts['os_family'] | lower) != 'debian'
    tags:
      - devops
      - devops_tools
      - dotlocal_pyenv_install
      - install
  - role: homeshick
    vars:
      castles:
        - uri: git@github.com:pedrohdz/dr-vimfiles-devops.git
    tags:
      - devops
      - devops_homeshick
      - homeshick
      - install
...
