---
dependencies:
  - role: common
  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: awscli
          version: '1.18.5'
          bin_files:
            - aws
            - aws_completer
        - package: jmespath-terminal
          version: '0.2.1'
          bin_files:
            - jpterm
        - package: netaddr
        - package: yamllint
          version: '1.20.0'
    tags:
      - devops
      - devops_tools
      - dotlocal_pyenv_install
      - install
  - role: dotlocal-pyenv-install
    vars:
      packages:
        - package: ansible-lint
          version: '4.2.0'
    when: (ansible_facts['os_family'] | lower) != 'debian'
    tags:
      - devops
      - devops_tools
      - dotlocal_pyenv_install
      - install
...
